import { Challenge, Pillar, PillarId } from './types';

export const PILLARS: Record<PillarId, Pillar> = {
  conexion: {
    name: 'Conexión y Propósito',
    sub: 'Quién eres y qué te rodea',
    icon: 'HeartPulse',
    clr: 'text-amber-400',
    bg: 'bg-amber-400/10',
  },
  ciudadania: {
    name: 'Ciudadanía Activa',
    sub: 'Tu comunidad, tu responsabilidad',
    icon: 'Users',
    clr: 'text-emerald-400',
    bg: 'bg-emerald-400/10',
  },
  habilidades: {
    name: 'Habilidades Reales',
    sub: 'Lo que sabes hacer importa',
    icon: 'Wrench',
    clr: 'text-orange-400',
    bg: 'bg-orange-400/10',
  },
  desafio: {
    name: 'Desafío Personal',
    sub: 'Enfrentar lo que te forma',
    icon: 'Flame',
    clr: 'text-cyan-400',
    bg: 'bg-cyan-400/10',
  },
};

export const REFLECTIVE_FEEDBACK: Record<PillarId, string[]> = {
  conexion: [
    'Tus ojos vieron lo que otros pasan por alto. Eso es una habilidad real.',
    'Hiciste algo bueno sin que nadie lo supiera. Eso no se compra con nada.',
    'Entender lo que sostiene tu mundo te hace más fuerte que los que no lo ven.',
    'Comparar realidades no es para sentir culpa: es para abrir los ojos.'
  ],
  ciudadania: [
    'Mapear lo que falta es el primer paso para cambiarlo. Ya empezaste.',
    'Conocer el origen de lo que consumes te da poder sobre tus decisiones.',
    'Las historias de los mayores son mapas del futuro. Tú la guardaste.',
    'Reconocer a quien nadie ve es un acto de justicia. Lo hiciste.'
  ],
  habilidades: [
    'Un nudo bien hecho puede salvar una vida. Ahora tus manos saben hacerlo.',
    'Construir con lo que hay es la habilidad más real que existe.',
    'Si te pierdes sin teléfono, hoy sabes cómo volver.',
    'Cocinar con poco no es carencia: es inteligencia. Hoy lo demostraste.'
  ],
  desafio: [
    'Caminar y observar a la vez es una superpotencia que casi nadie practica.',
    'El aburrimiento es donde nacen las ideas. Encontraste las tuyas.',
    'Saber qué hacer en una emergencia te convierte en alguien de confianza.',
    'Iniciar una conversación difícil exige más coraje que cualquier desafío físico.'
  ],
};

export const CHALLENGES: Challenge[] = [
  // --- Pillar: CONEXIÓN Y PROPÓSITO ---
  {
    id: 1,
    pil: 'conexion',
    icon: 'Clock',
    title: '15 Minutos que Nadie Se Toma',
    obj: 'Detente en un lugar que recorres todos los días pero donde nunca te detienes. Quédate 15 minutos en silencio. Observa todo lo que ocurre.',
    vr: {
      u: 'Una esquina transcurrida, parada de autobús o negocio que pasas a diario sin mirar.',
      c: 'La entrada de tu escuela, plaza local o centro comunitario.',
      r: 'Un punto del sendero o camino vecinal que recorres cada día sin detenerte.',
    },
    eqp: 'individual',
    safe: [
      'Revisa el clima. Si llueve o hace frío extremo, elige un lugar con techo seguro.',
      'Elige un lugar público seguro y visible. No te aísles en zonas solitarias.',
      'Si algún desconocido te pregunta qué haces, responde educadamente: "estoy descansando un momento".',
      'Asegúrate de que tu tutor sabe exactamente dónde estás y lleva tu teléfono cargado.',
      'Si tomas notas o fotos de apoyo, no incluyas rostros de desconocidos ni datos privados.',
    ],
    kw: ['silencio', 'observe', 'veo', 'pasaba', 'descubri', 'escucho', 'miro', 'detengo', 'lugar', 'ruido', 'calma', 'gente', 'tiempo', 'esquina', 'parada'],
    vq: null,
    exp: 50,
    rew: {
      name: 'Observador',
      icon: 'Eye',
    },
    hint: 'Si le contaras a un amigo lo que vieron tus ojos hoy, ¿qué le dirías que nadie más nota?',
  },
  {
    id: 2,
    pil: 'conexion',
    icon: 'HeartHandshake',
    title: 'El Trabajo Invisible',
    obj: 'Identifica a alguien cuyo esfuerzo diario mantiene limpio, seguro o funcional tu entorno pero que casi nadie reconoce. Realiza un pequeño acto de agradecimiento anónimo por esa persona.',
    vr: {
      u: 'La persona que barre tu calle, recolecta material reciclable o cuida la entrada del edificio.',
      c: 'Quien prepara alimentos en el comedor comunitario, limpia la escuela o asiste a los niños del vecindario.',
      r: 'La persona que trabaja la tierra vecina, repara los caminos locales o cuida de los canales de agua.',
    },
    eqp: 'individual',
    safe: [
      'Realiza la actividad durante el día. Evita las horas de la noche.',
      'No entres a propiedades privadas sin autorización explícita.',
      'Conserva tu anonimato; el valor está en el gesto generoso sin buscar crédito personal.',
      'Asegúrate de que tu tutor conoce el área donde realizarás el agradecimiento.',
      'No publiques fotos de la persona ni de su lugar de trabajo sin su consentimiento formal.',
    ],
    kw: ['invisible', 'reconoce', 'anonimo', 'nadie', 'trabajo', 'hice', 'persona', 'esfuerzo', 'agradecer', 'silencio', 'barre', 'limpia', 'gracias', 'limpieza', 'vecino'],
    vq: null,
    exp: 50,
    rew: {
      name: 'Mano Invisible',
      icon: 'Heart',
    },
    hint: 'Si esa persona supiera que alguien notó su esfuerzo hoy, ¿cómo crees que se sentiría? Escríbele un mensaje como si le hablaras directamente.',
  },
  {
    id: 3,
    pil: 'conexion',
    icon: 'Search',
    title: 'Lo que Sostiene Todo',
    obj: 'Encuentra tres elementos de infraestructura o roles comunitarios que si desaparecieran mañana, harían colapsar la rutina de tu vecindario de inmediato.',
    vr: {
      u: 'Camina por tu cuadra. Identifica cableados, registros de agua, señales de tránsito o semáforos clave.',
      c: 'Recorre las inmediaciones de tu comunidad: tomas de agua, almacenes de abasto o transporte vecinal.',
      r: 'Observa tu camino o sendero: puentes rústicos, pozos comunales o centros de acopio agrícola.',
    },
    eqp: 'individual',
    safe: [
      'Mantente en vías seguras e iluminadas. No cruces calles de forma imprudente.',
      'No manipules la infraestructura física ni abras cajas de control. Solo debes observar.',
      'Si alguien te pregunta qué haces, di amablemente: "estoy haciendo una investigación escolar sobre mi comunidad".',
      'Informa a tu tutor de tu ruta aproximada antes de iniciar.',
    ],
    kw: ['sostiene', 'invisible', 'tuberia', 'alcantarilla', 'poste', 'cambia', 'funciona', 'nota', 'encuentro', 'infraestructura', 'persona', 'luz', 'agua', 'cable', 'transito'],
    vq: null,
    exp: 55,
    rew: {
      name: 'Ojo Clínico',
      icon: 'Award',
    },
    hint: 'Si esos tres elementos desaparecieran mañana de golpe, ¿cómo se vería afectada tu rutina diaria? Escríbelo con detalle.',
  },
  {
    id: 4,
    pil: 'conexion',
    icon: 'Scale',
    title: 'Lo que Tengo y lo que Falta',
    obj: 'Haz una pausa para comparar honestamente tu vida cotidiana, recursos y oportunidades con los de un joven que resida en una realidad geográfica o social completamente distinta de tu país.',
    vr: {
      u: 'Investiga o reflexiona sobre la vida de un joven de una comunidad indígena de montaña o costa.',
      c: 'Compara tus recursos con los de alguien en una región rural que carece de internet y electricidad.',
      r: 'Analiza cómo cambia tu día comparado con un joven que vive en una megalópolis industrial de alta densidad.',
    },
    eqp: 'individual',
    safe: [
      'Esta es una actividad principalmente de reflexión mental; no necesitas salir de casa.',
      'Si entrevistas a alguien, sé sumamente respetuoso y pide su consentimiento previo.',
      'Habla con tu tutor si estas reflexiones te generan emociones fuertes o preguntas sobre desigualdad social.',
    ],
    kw: ['tengo', 'falta', 'diferencia', 'realidad', 'pais', 'comparo', 'oportunidad', 'vida', 'condiciones', 'privilegio', 'desigualdad', 'suerte', 'casa', 'internet', 'recursos'],
    vq: null,
    exp: 50,
    rew: {
      name: 'Mirada Clara',
      icon: 'BookOpen',
    },
    hint: 'Escríbete una carta breve a ti mismo para leer en 5 años: ¿qué es lo que más deseas valorar y no olvidar jamás sobre las diferencias que analizaste hoy?',
  },

  // --- Pillar: CIUDADANÍA ACTIVA ---
  {
    id: 5,
    pil: 'ciudadania',
    icon: 'Map',
    title: 'El Derecho al Espacio Común',
    obj: 'Mapea y documenta al menos 5 fallos de infraestructura o servicios que requieran atención en tu espacio público más cercano (baches, falta de luz, acumulación de basura, aceras rotas).',
    vr: {
      u: 'Recorre con tu compañero tu calle o el parque público más cercano.',
      c: 'Con tu equipo, dividan un sector de la comunidad para auditar colectivamente.',
      r: 'Inspecciona el camino principal de acceso a tu localidad o los bordes del río cercano.',
    },
    eqp: 'equipo',
    safe: [
      'Realicen el recorrido en horas con suficiente luz solar y siempre acompañados.',
      'No se adentren en callejones oscuros o propiedades privadas abandonadas.',
      'Si algún vecino pregunta con desconfianza, expliquen con una sonrisa que es un diagnóstico escolar.',
      'Sus tutores deben conocer de antemano el perímetro exacto de su recorrido.',
    ],
    kw: ['falta', 'alumbrado', 'acera', 'verde', 'drenaje', 'barrio', 'servicio', 'mapeo', 'calle', 'espacio', 'publico', 'cinco', 'basura', 'foco', 'bache', 'roto'],
    vq: '¿Cuántos servicios o fallos de infraestructura identificó tu compañero de equipo?',
    exp: 60,
    rew: {
      name: 'Mapeador',
      icon: 'MapPin',
    },
    hint: 'Si tuvieras la oportunidad de mostrarle este informe al alcalde o jefe de manzana, ¿qué le dirías para convencerle de priorizar estas reparaciones?',
  },
  {
    id: 6,
    pil: 'ciudadania',
    icon: 'Droplet',
    title: 'La Tierra que Nos Sostiene',
    obj: 'Investiga el origen exacto del agua que bebes a diario y los alimentos que llegan a tu mesa. Descubre cuál es el primer eslabón de esa cadena en tu localidad (pozo, acuífero, huerto, mercado de productores).',
    vr: {
      u: 'Investiga el nombre de la represa, planta potabilizadora o acuífero de tu ciudad, y de dónde se surte tu mercado local.',
      c: 'Visita con tu tutor un pozo de bombeo comunitario o un estanque de almacenamiento vecinal.',
      r: 'Sigue el trayecto del agua de tu manantial, canal de riego o pozo artesanal, así como el origen de tus vegetales de autoconsumo.',
    },
    eqp: 'individual',
    safe: [
      'No te acerques a ríos caudalosos, represas o pozos profundos sin la presencia física de tu tutor.',
      'No consumas agua directamente de fuentes naturales o industriales sin filtrar ni hervir.',
      'Informa a tu tutor de tu salida; prefiere realizar la investigación apoyándote en enciclopedias o internet si el acceso físico es riesgoso.',
    ],
    kw: ['agua', 'comida', 'origen', 'fuente', 'mercado', 'camino', 'investigue', 'viene', 'tratamiento', 'recurso', 'abasto', 'pozo', 'agricultura', 'rio', 'alimento'],
    vq: null,
    exp: 55,
    rew: {
      name: 'Rastreador',
      icon: 'Compass',
    },
    hint: 'Si un niño pequeño te preguntara con curiosidad: "¿de dónde sale el agua que sale de la llave de la cocina?", ¿cómo se lo explicarías paso a paso de forma divertida?',
  },
  {
    id: 7,
    pil: 'ciudadania',
    icon: 'Mic',
    title: 'Historias que No Se Cuentan',
    obj: 'Entrevista a un adulto mayor de tu comunidad (un abuelo, un vecino longevo o un comerciante veterano) para rescatar la memoria histórica de cómo era este lugar hace 40 o 50 años.',
    vr: {
      u: 'Conversa con un vecino jubilado de tu edificio o condominio sobre el cambio de la colonia.',
      c: 'Con tu equipo, visiten a un sabio o líder comunitario mayor en un espacio público o su taller.',
      r: 'Entrevista a un campesino o ejidatario mayor acerca de cómo eran los bosques, milpas o arroyos en su niñez.',
    },
    eqp: 'equipo',
    safe: [
      'Realiza la entrevista en un ambiente cómodo, iluminado y en compañía de un tutor o compañeros.',
      'Sé extremadamente paciente y respetuoso. Pregunta antes de tomar fotos, grabar voz o hacer anotaciones.',
      'No acudas solo a la casa de un desconocido sin el acompañamiento directo de un adulto tutor.',
    ],
    kw: ['entrevista', 'historia', 'cambio', 'mayor', 'antes', 'barrio', 'comunidad', 'joven', 'recuerdo', 'faltaba', 'abuelo', 'anciano', 'tradicion', 'años', 'antiguo'],
    vq: '¿Cómo se llamaba la persona mayor que entrevistó tu compañero y qué edad aproximada tenía?',
    exp: 60,
    rew: {
      name: 'Cronista',
      icon: 'Clipboard',
    },
    hint: '¿Qué anécdota o cambio del lugar de los que te contaron te impactó o conmovió más? Escríbela como si redactaras una crónica periodística.',
  },
  {
    id: 8,
    pil: 'ciudadania',
    icon: 'Heart',
    title: 'Héroes Sin Estatua',
    obj: 'Identifica a un líder social, vecino solidario o voluntario que trabaje activamente para mejorar las condiciones de tu entorno sin recibir pago ni reconocimiento público. Prepárales una carta o detalle sincero de gratitud.',
    vr: {
      u: 'El vecino que cuida a los perros callejeros del sector, organiza limpieza de parques o reparte abrigos.',
      c: 'Quien coordina un taller gratuito para jóvenes o recolecta juguetes para las familias necesitadas.',
      r: 'La partera comunitaria, el guardabosques voluntario o quien organiza faenas colectivas para desazolvar caminos.',
    },
    eqp: 'equipo',
    safe: [
      'No te expongas a situaciones incómodas ni entregues cartas a personas con conductas extrañas o violentas.',
      'El obsequio o carta de agradecimiento debe entregarse preferentemente en un espacio de acceso público.',
      'Mantén a tus padres o tutores informados y solicita su compañía durante el contacto.',
    ],
    kw: ['reconoce', 'heroe', 'comunidad', 'sin estatua', 'mejora', 'nadie', 'nombre', 'agradece', 'nota', 'persona', 'gracias', 'carta', 'ayuda', 'voluntario', 'solidaridad'],
    vq: '¿Qué labor altruista realiza el "Héroe sin Estatua" que seleccionó y agradeció tu compañero?',
    exp: 60,
    rew: {
      name: 'Reconocedor',
      icon: 'Smile',
    },
    hint: 'Si este héroe anónimo llegara a leer tus palabras sinceras hoy, ¿qué impacto crees que tendría en su motivación diaria? Escribe las palabras que le dedicaste.',
  },

  // --- Pillar: HABILIDADES REALES ---
  {
    id: 9,
    pil: 'habilidades',
    icon: 'Activity',
    title: 'El Nudo que Salva',
    obj: 'Aprende y domina la realización de 3 nudos técnicos esenciales para la vida real: el nudo en Ocho (seguridad), el Ballestrinque (amarre) y el As de Guía (rescate).',
    vr: {
      u: 'Consigue un tramo de cuerda o cable en desuso en tu casa y practica los nudos fijándolos a una silla.',
      c: 'Con tu equipo en la escuela, realicen una demostración de velocidad de nudos.',
      r: 'Practica la aplicación real de estos nudos asegurando una carga de leña o amarrando un poste en el corral.',
    },
    eqp: 'equipo',
    safe: [
      'No utilices cuerdas desgastadas que se puedan romper violentamente y lastimar tus manos.',
      'BAJO NINGUNA CIRCUNSTANCIA te coloques cuerdas o lazos alrededor del cuello o extremidades.',
      'No intentes trepar a árboles o muros usando nudos que acabas de aprender sin arnés profesional y supervisión experta.',
      'Utiliza tijeras o navajas únicamente bajo la supervisión rigurosa de un tutor adulto.',
    ],
    kw: ['nudo', 'ocho', 'ballestrinque', 'as de guia', 'situacion', 'real', 'cuerda', 'amarrar', 'carga', 'soltar', 'seguridad', 'practique', 'amarre', 'lazo', 'soga'],
    vq: '¿Cuál de los 3 nudos le costó más trabajo dominar a tu compañero de equipo hoy?',
    exp: 55,
    rew: {
      name: 'Nudo Maestro',
      icon: 'Link',
    },
    hint: 'Describe una situación de emergencia real (un rescate, un amarre de carga peligrosa o un viento fuerte) donde saber hacer un "As de Guía" sea crucial.',
  },
  {
    id: 10,
    pil: 'habilidades',
    icon: 'Home',
    title: 'Refugio con lo que Hay',
    obj: 'Imagina una situación de emergencia donde debas construir un refugio temporal en menos de 10 minutos. Diseña y arma un prototipo funcional resistente al viento usando únicamente materiales que tengas a mano.',
    vr: {
      u: 'Usa mesas, sillas de patio, sábanas viejas, ganchos de ropa y cuerdas en tu sala o terraza.',
      c: 'En el patio escolar o centro vecinal, utilicen lonas de desecho, tubos de PVC y mecate.',
      r: 'Construye un cobertizo improvisado usando ramas secas caídas, paja, hojas de plátano o maguey y mecate.',
    },
    eqp: 'equipo',
    safe: [
      'No construyas el refugio al aire libre si se avecina una tormenta eléctrica o ráfagas de viento peligrosas.',
      'No utilices materiales pesados, filosos, láminas oxidadas o maderas podridas que puedan colapsar sobre ti.',
      'Asegúrate de que la estructura tenga una salida de emergencia amplia y despejada.',
      'Tu tutor debe revisar físicamente la firmeza de la estructura antes de que entres en ella.',
    ],
    kw: ['refugio', 'construi', 'materiales', 'viento', 'sillas', 'cuerda', 'lona', 'ramas', 'resiste', '5 minutos', 'diez', 'cobertizo', 'madera', 'sabana', 'estructura'],
    vq: '¿Qué objeto o material de la casa o entorno usó tu compañero como base para sostener el techo?',
    exp: 65,
    rew: {
      name: 'Constructor',
      icon: 'Shield',
    },
    hint: '¿Cómo lograste resolver la estabilidad del techo frente a una ráfaga de viento imaginaria? Explica el secreto del diseño de tu refugio.',
  },
  {
    id: 11,
    pil: 'habilidades',
    icon: 'Navigation',
    title: 'Orientación Sin Pantalla',
    obj: 'Encuentra la dirección del Norte geográfico sin utilizar tu teléfono móvil, internet ni brújula digital, guiándote por el sol, la sombra de un poste a mediodía o la constelación de estrellas de noche.',
    vr: {
      u: 'Sal a un patio o balcón a mediodía, clava un palillo en el suelo y marca la dirección en que avanza su sombra.',
      c: 'Organicen un rally en el parque con tu equipo para que cada quien halle el Norte con métodos de rastreo natural.',
      r: 'Alinea dos estacas con la Estrella Polar en el campo abierto durante una noche despejada.',
    },
    eqp: 'equipo',
    safe: [
      'Si el cielo está densamente nublado o hay tormenta, pospone la actividad hasta que mejoren las condiciones.',
      'No te adentres en bosques, cerros o áreas despobladas de noche para buscar estrellas.',
      'Mantente con tu equipo de juego en zonas familiares y seguras.',
      'El tutor debe establecer un punto de encuentro visible antes de iniciar el ejercicio de orientación.',
    ],
    kw: ['norte', 'sol', 'sombra', 'estrella', 'polar', 'brujula', 'orientar', 'perdido', 'telefono', 'ruta', 'volver', 'sur', 'este', 'oeste', 'cielo'],
    vq: '¿Qué método natural empleó tu compañero para ubicar los puntos cardinales en su ejercicio?',
    exp: 55,
    rew: {
      name: 'Brújula Humana',
      icon: 'Compass',
    },
    hint: 'Si te encontraras perdido en medio de la naturaleza sin batería en tu celular, ¿qué puntos de referencia naturales buscarías primero para trazar una ruta de regreso segura?',
  },
  {
    id: 12,
    pil: 'habilidades',
    icon: 'Flame',
    title: 'Cocinar con Casi Nada',
    obj: 'Abre la despensa o cocina de tu casa y utiliza exactamente 3 ingredientes básicos que encuentres para preparar un alimento caliente nutritivo y comestible, sin seguir ninguna receta de internet.',
    vr: {
      u: 'Usa ingredientes comunes en el refrigerador (huevo, tortilla fría, frijoles) para crear una comida caliente.',
      c: 'Organicen una comida cooperativa con tu tutor donde cada miembro aporte un solo ingrediente sorpresa.',
      r: 'Prepara una comida rústica usando maíz molido, hierbas silvestres comestibles locales y sal en tu fogón.',
    },
    eqp: 'individual',
    safe: [
      'SI VAS A UTILIZAR LA ESTUFA O FUEGO, LA PRESENCIA FÍSICA Y SUPERVISIÓN DE TU TUTOR ES OBLIGATORIA.',
      'Manipula cuchillos, peladores y sartenes calientes con extremo cuidado y lentitud.',
      'Asegúrate de tener un vaso de agua o un paño húmedo cerca del área de cocción para emergencias menores.',
      'Verifica la caducidad y buen estado de los 3 ingredientes antes de consumirlos.',
    ],
    kw: ['ingrediente', 'receta', 'resultado', 'tres', 'poco', 'resolver', 'creativo', 'fuego', 'estufa', 'sabroso', 'huevo', 'frijol', 'cocinar', 'comer', 'alimento'],
    vq: null,
    exp: 60,
    rew: {
      name: 'Chef Improvisado',
      icon: 'Flame',
    },
    hint: '¿Cuáles fueron tus 3 ingredientes elegidos y cuál fue el veredicto del sabor de tu platillo según tu tutor? Describe el proceso de creación.',
  },

  // --- Pillar: DESAFÍO PERSONAL ---
  {
    id: 13,
    pil: 'desafio',
    icon: 'Footprints',
    title: '5 Kilómetros de Verdad',
    obj: 'Recorre a pie una distancia de 5 kilómetros por tu localidad de forma consciente. Durante el trayecto, cuenta cuántas personas te miran directo a los ojos, cuántas te ignoran por completo y cuántas te devuelven una sonrisa.',
    vr: {
      u: 'Traza una ruta segura que cruce tu colonia de extremo a extremo pasando por avenidas principales.',
      c: 'Caminen con su equipo de juego rodeando el perímetro de su comunidad de forma organizada.',
      r: 'Recorre a pie el sendero entre tu localidad y el pueblo vecino de ida y vuelta.',
    },
    eqp: 'equipo',
    safe: [
      'Evita las horas de calor extremo (de 11:00 am a 4:00 pm). Lleva al menos 500 ml de agua para mantenerte hidratado.',
      'Lleva calzado cómodo y calcetines gruesos. Si sientes dolor en las articulaciones, detente inmediatamente.',
      'No camines solo. Realiza el desafío con tu equipo de compañeros o tu tutor, y nunca aceptes viajes en auto de extraños.',
      'Tu tutor debe dar el visto bueno a la ruta elegida antes de iniciar la marcha.',
    ],
    kw: ['kilometro', 'camine', 'personas', 'miraron', 'ignoraron', 'sonrieron', 'comunidad', 'observe', 'ruta', 'calle', 'cinco', 'distancia', 'pasos', 'marcha', 'andar'],
    vq: '¿Cuántas sonrisas amigables logró contabilizar tu compañero de equipo durante su caminata de 5 km?',
    exp: 65,
    rew: {
      name: 'Explorador',
      icon: 'TrendingUp',
    },
    hint: '¿Qué conclusiones sacas sobre cómo nos relacionamos los seres humanos en el espacio público? ¿Crees que somos más indiferentes de lo que pensamos?',
  },
  {
    id: 14,
    pil: 'desafio',
    icon: 'Smartphone',
    title: '24 Horas Desconectado',
    obj: 'Apaga por completo todas tus pantallas (teléfono inteligente, televisión, consola de videojuegos, tableta y computadora) desde la salida del sol hasta la puesta. Dedica ese tiempo a actividades manuales, de lectura, al aire libre o a convivir.',
    vr: {
      u: 'Guarda tus dispositivos en un cajón y no los toques durante un día completo de fin de semana.',
      c: 'Tu equipo de juego realiza el apagón tecnológico el mismo día y acuerdan reunirse en el parque de la comunidad.',
      r: 'Pasa todo el día en el campo, ayudando en las labores o leyendo bajo un árbol sin pantallas.',
    },
    eqp: 'equipo',
    safe: [
      'Si el aburrimiento o la ansiedad te abruman, realiza respiraciones profundas, dibuja o platica con tus familiares.',
      'Si ocurre una emergencia médica o familiar REAL, rompe el ayuno digital de inmediato; la seguridad es siempre primero.',
      'Informa a tus amigos un día antes para que sepan que no responderás mensajes de texto o llamadas no urgentes.',
      'Tus padres deben estar enterados y de acuerdo con el día seleccionado para el reto.',
    ],
    kw: ['pantalla', 'desconectado', 'aburrimiento', 'descubri', 'horas', 'libro', 'converse', 'jugue', 'ansiedad', 'silencio', 'familia', 'celular', 'telefono', 'apagado', 'tiempo'],
    vq: '¿Qué actividad creativa o juego tradicional realizó tu compañero para vencer el aburrimiento sin usar internet?',
    exp: 65,
    rew: {
      name: 'Despierto',
      icon: 'Zap',
    },
    hint: '¿Cuál fue el momento más difícil del día sin pantallas y qué descubriste sobre tu mente cuando dejas de recibir notificaciones digitales constantemente?',
  },
  {
    id: 15,
    pil: 'desafio',
    icon: 'AlertTriangle',
    title: 'Emergencia de Tu Realidad',
    obj: 'Identifica el tipo de desastre natural o emergencia comunitaria más probable en tu localidad (sismo, inundación, incendio forestal, helada). Investiga las recomendaciones de Protección Civil y diseña un Plan de Escape Familiar con tu hogar.',
    vr: {
      u: 'Investiga las zonas de evacuación por sismo o inundación en tu colonia y localiza las tomas de agua o hidrantes.',
      c: 'Reúne a tu familia para acordar un punto de encuentro seguro fuera del vecindario en caso de un siniestro.',
      r: 'Planea una ruta de evacuación rápida ante incendios de maleza, sequías extremas o desbordamiento de arroyos.',
    },
    eqp: 'individual',
    safe: [
      'Este desafío es estrictamente teórico y de planificación preventiva. NO provoques simulacros ruidosos que asusten a tus vecinos.',
      'Apóyate exclusivamente en fuentes de información oficiales y científicas de tu gobierno (Protección Civil o Bomberos).',
      'Si vas a entrevistar a un bombero o rescatista local, solicita la compañía directa de tu tutor.',
      'Asegúrate de que el plan de emergencia sea comprensible e incluyente para niños pequeños o adultos mayores en tu casa.',
    ],
    kw: ['emergencia', 'plan', 'familia', 'inundacion', 'incendio', 'sismo', 'practique', 'salida', 'punto de encuentro', 'proteccion', 'bomberos', 'civil', 'escape', 'ruta', 'ayuda'],
    vq: null,
    exp: 70,
    rew: {
      name: 'Preparado',
      icon: 'ShieldAlert',
    },
    hint: 'Si tuvieras únicamente 30 segundos para guiar a un niño de tu familia durante un sismo o inundación en casa, ¿cuáles serían tus 3 instrucciones clave de supervivencia?',
  },
  {
    id: 16,
    pil: 'desafio',
    icon: 'MessageSquare',
    title: 'La Conversación Difícil',
    obj: 'Identifica un tema importante que te genere nerviosismo o incomodidad hablar con tus padres o tutores (como tus miedos sobre el futuro, un conflicto, o un límite personal) e inicia esa conversación con valentía.',
    vr: {
      u: 'Aparta 20 minutos con tu tutor en un momento relajado en la sala de tu hogar para charlar a solas.',
      c: 'Comparte con tus amigos cercanos del equipo cuáles son los temas que más les asusta discutir con adultos.',
      r: 'Conversa con un familiar maduro mientras realizan una caminata tranquila en el campo.',
    },
    eqp: 'individual',
    safe: [
      'Elige un momento de calma absoluta; no intentes iniciar esta conversación en medio de una discusión activa.',
      'La conversación debe ser respetuosa, sincera y constructiva. Si los ánimos se tensan, puedes decir: "me gustaría pausar un momento y continuar mañana".',
      'Si el tema que necesitas tratar involucra abuso, violencia de cualquier tipo o peligro inminente, recurre de inmediato a las autoridades, línea de ayuda 112, bomberos o a un adulto de total confianza.',
      'No divulgues la información privada o íntima de tu familia a personas ajenas.',
    ],
    kw: ['conversacion', 'dificil', 'incomoda', 'hable', 'senti', 'miedo', 'emociones', 'violencia', 'conflicto', 'papa', 'mama', 'amigo', 'valentia', 'charla', 'hablar'],
    vq: null,
    exp: 70,
    rew: {
      name: 'Valiente',
      icon: 'Flame',
    },
    hint: '¿Cómo lograste vencer el temor inicial de tocar este tema? Si un compañero te dijera "no me atrevo a hablar de eso en casa", ¿qué consejo le darías basándote en lo que viviste hoy?',
  },
];
